@vehiculos_api_HostAddress = http://localhost:5125
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0b21hcy5lbWFydEBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc2NjA0NDU5NywiaXNzIjoidmVoaWN1bG9zLWFwaSIsImF1ZCI6InZlaGljdWxvcy1hcGkifQ.BgVtVE-qWs8ojpJwq66y6HOqk3JblfysR3jEUcc_gxA

POST {{vehiculos_api_HostAddress}}/users/signup
Content-Type: application/json
Accept: application/json

{
  "firstName": "Candela",
  "lastName": "Reynoso",
  "email": "candela@gmail.com",
  "password": "123456",
  "roleId": 2
}

###

POST {{vehiculos_api_HostAddress}}/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "tomas.emart@gmail.com",
  "password": "123456"
}

###

GET {{vehiculos_api_HostAddress}}/users
Accept: application/json
Authorization: Bearer {{jwt}}