@vehiculos_api_HostAddress = http://localhost:5125
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0b21hc0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc2NjI4NTExNiwiaXNzIjoidmVoaWN1bG9zLWFwaSIsImF1ZCI6InZlaGljdWxvcy1hcGkifQ.CMK0KLv6LXwwwVrw4sWHOo7P3svDiNlnRp0huJ0FSIY

POST {{vehiculos_api_HostAddress}}/vehicles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Porsche",
  "model": "911",
  "year": 1986,
  "kilometers": 45200,
  "vehicleTypeId": 1
}

###

GET {{vehiculos_api_HostAddress}}/vehicles
Accept: application/json
Authorization: Bearer {{jwt}}

###

PATCH {{vehiculos_api_HostAddress}}/vehicles/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Ferrari",
  "model": "F45",
  "year": 1990
}

###

GET {{vehiculos_api_HostAddress}}/vehicles/1/maintenance
Accept: application/json
Authorization: Bearer {{jwt}}