@vehiculos_api_HostAddress = http://localhost:5125
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0b21hcy5lbWFydEBnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc2ODIyNzgxNywiaXNzIjoidmVoaWN1bG9zLWFwaSIsImF1ZCI6InZlaGljdWxvcy1hcGkifQ.d3CYmATo6w44a_LXOfm71-9qGhf35pUf40QoD6iZT44

POST {{vehiculos_api_HostAddress}}/vehicles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Porsche",
  "model": "911",
  "year": 1986,
  "kilometers": 45200,
  "vehicleTypeId": 1
}

###

GET {{vehiculos_api_HostAddress}}/vehicles
Accept: application/json
Authorization: Bearer {{jwt}}

###

GET {{vehiculos_api_HostAddress}}/vehicles/5
Accept: application/json
Authorization: Bearer {{jwt}}

###

PATCH {{vehiculos_api_HostAddress}}/vehicles/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Ferrari",
  "model": "F45",
  "year": 1990
}

###

GET {{vehiculos_api_HostAddress}}/vehicles/5/maintenance
Accept: application/json
Authorization: Bearer {{jwt}}

###
GET {{vehiculos_api_HostAddress}}/vehicles/5/kilometers
Accept: application/json
Authorization: Bearer {{jwt}}

###
PATCH {{vehiculos_api_HostAddress}}/vehicles/5/kilometers
Accept: application/json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "kilometers": 73000
}

###
DELETE {{vehiculos_api_HostAddress}}/vehicles/4
Accept: application/json
Authorization: Bearer {{jwt}}