@vehiculos_api_HostAddress = http://localhost:5125
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJ0b21hc0BnbWFpbC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbiIsImV4cCI6MTc2NjEzNjQ2MCwiaXNzIjoidmVoaWN1bG9zLWFwaSIsImF1ZCI6InZlaGljdWxvcy1hcGkifQ.geE69BFWw8ztPDAlnN8kjcn-YJDKHhUqyb_mqP0JMU0

POST {{vehiculos_api_HostAddress}}/vehicles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Ferrari",
  "model": "F40",
  "year": 1994,
  "kilometers": 60200,
  "vehicleTypeId": 1
}

###

GET {{vehiculos_api_HostAddress}}/vehicles
Accept: application/json
Authorization: Bearer {{jwt}}

###

PATCH {{vehiculos_api_HostAddress}}/vehicles/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Ferrari",
  "model": "F45",
  "year": 1990
}

###

GET {{vehiculos_api_HostAddress}}/vehicles/1/maintenance
Accept: application/json
Authorization: Bearer {{jwt}}