@vehiculos_api_HostAddress = http://localhost:5125

POST {{vehiculos_api_HostAddress}}/api/users/signup
Content-Type: application/json
Accept: application/json

{
  "firstName": "Candela",
  "lastName": "Reynoso",
  "email": "candela@gmail.com",
  "password": "123456",
  "roleId": 2
}

###

POST {{vehiculos_api_HostAddress}}/api/users/login
Content-Type: application/json
Accept: application/json

{
  "email": "candela@gmail.com",
  "password": "123456"
}

###

@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJjYW5kZWxhQGdtYWlsLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IlVzZXIiLCJleHAiOjE3NjU5NTIxMzYsImlzcyI6InZlaGljdWxvcy1hcGkiLCJhdWQiOiJ2ZWhpY3Vsb3MtYXBpIn0.ds13izJON_IP_i6rmf61XfFJ0v7rMTr_l6U_HsxzIDQ

GET {{vehiculos_api_HostAddress}}/api/users
Accept: application/json
Authorization: Bearer {{jwt}}


###

POST {{vehiculos_api_HostAddress}}/api/vehicles
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Volkswagen",
  "model": "Golf",
  "year": 2006,
  "kilometers": 199500,
  "vehicleTypeId": 1
}

###

GET {{vehiculos_api_HostAddress}}/api/vehicles
Accept: application/json
Authorization: Bearer {{jwt}}

###
}

###

PATCH {{vehiculos_api_HostAddress}}/api/vehicles/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt}}

{
  "brand": "Ferrari",
  "model": "F45",
  "year": 1990
}