@vehiculos_api_HostAddress = http://localhost:5125

POST {{vehiculos_api_HostAddress}}/api/users/signup
Content-Type: application/json
Accept: application/json

{
  "firstName": "Tomás",
  "lastName": "Martínez",
  "email": "tomas.emart@gmail.com",
  "password": "123456"
}

###
